spring:
  datasource:
    url: jdbc:h2:mem:quantivyx;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  redis:
    url: redis://localhost:6379/1
